<?php

use function PHPico\config;
use function PHPico\s;
?>

<?php $this->setLayout('layout') ?>

<?php $this->block('content');
    /* @var array $quote */
    [$author, $quoteText] = $quote;
?>

    <div class="quote">
        <div class="quoteText">
            <?php if (config('showQuote', false)): ?>
                <span class="quoteSymbol">&rdquo;</span>
            <?php endif; ?>
            <?= s($quoteText) ?>
        </div>
        <div class="author">&boxh; <?= s($author) ?></div>
    </div>

<?php $this->endblock('content') ?>
